### ISSUE TITLE
Wrong response code for MKD

### ISSUE THREAD

**Issue by crleblanc** [fclairamb/ftpserverlib#1]
I've been tracking down a small issue.  I'm using this ftp server in a new project and using a different ftp client to test it: github.com/jlaffaye/ftp.

Calling mkdir on the FTP server (MKD) replies with 250 which the ftp client assumes is an error since it expects 257 as defined in RFC 959 (https://www.w3.org/Protocols/rfc959/5_Declarative.html).

I'm unsure if it's best to modify the response from the server to be 257 or for the ftp client to accept either 250 and 257.  What's your preference?

Thanks, this is a nice little ftp server package.

**Comment by fclairamb** [comment]
You are so nice 😄 . My server is not respecting the RFC, so my preference is to fix it.

**Comment by fclairamb** [comment]
By the way what do you do with your FTP server ?

**Comment by crleblanc** [comment]
Thanks for the fix, that was quick!

I'm working on an ftp server as a front end for S3 called bucketFTP under the GeoNet user.  The repo is currently private but we'll open it up shortly.  We have a lot of field equipment that only supports uploads to FTP servers so this will give us an easy way to upload files to S3 for more reliable storage.  We can also enable triggers when a file comes into a bucket, such as updating a web page.

Several projects already existed to do this but we wanted something written in Go, running in a Docker container, that doesn't buffer files, uses environment variables for config, and is well tested (via CI).  So far it's looking like we'll do all of those things.

**Comment by fclairamb** [comment]
Very interesting. Doing a S3 connector should be fairly easy to do.

Don't hesitate to tell me if you have ideas around the library. My goal is to make it: stable, small (close to how golang is designed), fully-featured (support all frequently used FTP features).
