### ISSUE TITLE
ChmodFile is flickery

### ISSUE THREAD

**Issue by fahman** [fclairamb/ftpserverlib#114]
Assumption is that handle_files.go#handleCHMOD(params string) is doing incorrect conversion.

The line
https://github.com/fclairamb/ftpserver/blob/790cd46636c35d101d353f1e52db24b8f7e1d4a4/server/handle_files.go#L106

should actually be:

`modeNb, err := strconv.ParseUint(spl[0], 8, 32)`

**Comment by fclairamb** [comment]
Thank you, I just merged your PR.
