### ISSUE TITLE
Data dir setting not working

### ISSUE THREAD

**Issue by ernierasta** [fclairamb/ftpserverlib#116]
Hi,
on current master there is problem with `-data` cli parameter. It is passed, but at the end always / (main directory) is served.

This is quite huge problem. ;-)

**Comment by fclairamb** [comment]
This was indeed broken by #99. It's most probably something that needs to be fixed in the sample driver.

As always, please remember this is a library with a sample implementation, not an actual ftp server.

**Comment by sourcesoft** [comment]
Thanks for the fix in the latest PR, however I'm not sure about others but that didn't fix the issue in my case. I tried the default driver btw.
EDIT: Ignore whatever I just said, it's working. My driver sample was kinda broken.

**Comment by fclairamb** [comment]
Good!
