### ISSUE TITLE
ABOR support

### ISSUE THREAD

**Issue by drakkan** [fclairamb/ftpserverlib#173]
Hi,

this seems a basic FTP feature we should support it. Do you agree?

I'm quite busy at the moment however I'll try to work on this in the next weeks/months. 

We probably should refactor the [handleCommand](https://github.com/fclairamb/ftpserverlib/blob/master/client_handler.go#L229) method to execute the `STOR` and other commands that can be aborted in a separate goroutine to be able to receive the `ABOR` command.

**Comment by fclairamb** [comment]
I didn't know this command existed. You're becoming quite the FTP expert! 

This adds only more madness to the FTP protocol. I find it very strange to interrupt the synchronous flow of commands with asynchronous ones. This means that if a few commands are passed synchronously. Do you know any server that supports this command? I'd like to see how they handle the queuing of synchronous commands.

My goal is to make this library the most featured one, so we might as well support it.

How do you see this? 

It seems like the cleanest implementation would be to properly use `Context` throughout the API but at the same time as the `afero.Fs` API doesn't support it so he actual use-cases of having something to interrupt are pretty limited.

The way I see it is that we could:
- Mark a few commands as being "abortable"
- Once any of these commands are run, a context is initialized on the current connection and the command is run on another goroutine
- We continue to read commands. If we receive an `ABOR`, we cancel the context and that shall close the current connection on the current command execution. If we receive something else than`ABOR`, we can put it in a queue of commands and parse each of them at the end of the main command execution.

**Comment by drakkan** [comment]
Hi,

I think `ABOR` is supported by many, if not all, FTP servers. 

For what I understand from reading the [specs](https://tools.ietf.org/html/rfc959) FTP commands are generally sequential. But there are some command that require "special actions". These commands are `ABOR`, `STAT`, `QUIT`.

pyftpdlib [code](https://github.com/giampaolo/pyftpdlib/blob/master/pyftpdlib/handlers.py#L1459) should be easier to follow than ProFTPD or Pure-FTPd.

Regarding `ABOR` handling this is an extract from the specs

```
This command tells the server to abort the previous FTP
service command and any associated transfer of data.  The
abort command may require "special action", as discussed in
the Section on FTP Commands, to force recognition by the
server.  No action is to be taken if the previous command
has been completed (including data transfer).  The control
connection is not to be closed by the server, but the data
connection must be closed.

There are two cases for the server upon receipt of this
command: (1) the FTP service command was already completed,
or (2) the FTP service command is still in progress.

In the first case, the server closes the data connection
(if it is open) and responds with a 226 reply, indicating
that the abort command was successfully processed.

In the second case, the server aborts the FTP service in
progress and closes the data connection, returning a 426
reply to indicate that the service request terminated
abnormally.  The server then sends a 226 reply,
indicating that the abort command was successfully
processed.
```

I'll try to implement this feature, but I'm quite busy in this period, it could require some time
