### ISSUE TITLE
LIST -a option

### ISSUE THREAD

**Issue by drakkan** [fclairamb/ftpserverlib#174]
Hi,

I tested the library with `curlftpfs` it issue a `LIST` command passing the `-a` option and `ftpserverlib` search for a non-existing `-a` directory. Based on the doc [here](https://cr.yp.to/ftp/list.html):

"""
High-quality clients do not attempt to use these features. File selection and sorting are user-interface features that can and should be handled by the client.
"""

this simple patch fixes the issue

```
diff --git a/handle_dirs.go b/handle_dirs.go
index 16187e7..13f2f15 100644
--- a/handle_dirs.go
+++ b/handle_dirs.go
@@ -88,6 +88,10 @@ func (c *clientHandler) handlePWD() error {
 }
 
 func (c *clientHandler) handleLIST() error {
+	param := strings.ToLower(c.param)
+	if param == "-a" || param == "-l" || param == "-al" || param == "-la" {
+		c.param = ""
+	}
 	if files, err := c.getFileList(); err == nil || err == io.EOF {
 		if tr, errTr := c.TransferOpen(); errTr == nil {
 			err = c.dirTransferLIST(tr, files)
-- 
2.28.0
```

this is basically the same way that pyftpdlib handle [this](https://github.com/giampaolo/pyftpdlib/blob/master/pyftpdlib/handlers.py#L1501).

I'm unsure if add support for this feature and, if we decide to include this patch, if add a check to verify that a directory named `-a`, `-l` etc.  exists before discarding the param. What do you think about? Thank you

**Comment by fclairamb** [comment]
Wow, I didn't know [pyftpdlib](https://github.com/giampaolo/pyftpdlib). It serves exactly the same purpose as this library.

My general approach to that is both:
- We should support any mainstream client. The FTP protocol itself is a mess and the whole purpose of this library is to create a bridge between the legacy (FTP) and the new (Cloud services) worlds.
- I'd like the "dirty" parts of the FTP implementation to be identified as such

So I would be in favor of adding a `DisableLISTArgs bool` parameter in the `Settings` for people who would want a clean implementation of the server and this code enclsoed within a `if ! settings.DisableLISTArgs {`.

@drakkan what do you think?

**Comment by drakkan** [comment]
I agree, I'll try to check if a directory named `-a`, `-l` etc. exists before discarding the param, this feature should be quite easy to implement.
