### ISSUE TITLE
TLS and active FTP transfer

### ISSUE THREAD

**Issue by rel33** [fclairamb/ftpserverlib#177]
Hello,

I use sftpgo. I noticed, that TLS is working for login and PASV transfers, but then data transfer is unencrypted.
As sftpgo is using ftpserverlib, I suspect bug may be in ftpserverlib.

Filezilla is by default using PASV mode, then one should set Active mode in configuration, before trying to connect.

Summary:
- login using AUTH TLS works
- active FTP connection is established (from port 20 to high port of the Filezilla client)
- active FTP data transfer is unencrypted, then fails, as client expect it to be encrypted the same way as control FTP channel.

Result in Filezilla:

Status:	Connecting to 172.31.SER.VER:21...
Status:	Connection established, waiting for welcome message...
Response:	220 SFTPGo 1.0.0-dev ready
Command:	AUTH TLS
Response:	234 AUTH command ok. Expecting TLS Negotiation.
Status:	Initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established.
Command:	USER test
Response:	331 OK
Command:	PASS ********
Response:	230 Password ok, continue
Command:	CLNT FileZilla
Response:	200 Good to know
Command:	OPTS UTF8 ON
Response:	200 I'm in UTF8 only anyway
Command:	PBSZ 0
Response:	200 Whatever
Command:	PROT P
Response:	200 OK
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is the current directory
Command:	TYPE I
Response:	200 Type set to binary
Command:	PORT 172,31,CLI,ENT,50,172
Response:	200 PORT command successful
Command:	MLSD
Response:	150 Using transfer connection
Error:	GnuTLS error -15: An unexpected TLS packet was received.
Error:	Transfer connection interrupted: ECONNABORTED - Connection aborted
Response:	226 Closing transfer connection
Error:	Failed to retrieve directory listing

Unencrypted data (directory listing) can be seen by looking on data transfer from port 20 of the FTP server.

**Comment by drakkan** [comment]
Hi, 

I think you are right, ftpserverlib seems to always open active connections [unencrypted](https://github.com/fclairamb/ftpserverlib/blob/master/transfer_active.go#L50).

I will try to fix this issue but as I am quite busy right now it may take a while. Thank you for using SFTPGo!

**Comment by drakkan** [comment]
Hi, 

I did a quick test, the following patch seems to fix the issue for me:

```
diff --git a/transfer_active.go b/transfer_active.go
index 3255b53..a0f0d58 100644
--- a/transfer_active.go
+++ b/transfer_active.go
@@ -2,6 +2,7 @@
 package ftpserver
 
 import (
+       "crypto/tls"
        "errors"
        "fmt"
        "net"
@@ -21,9 +22,20 @@ func (c *clientHandler) handlePORT() error {
 
        c.writeMessage(StatusOK, "PORT command successful")
 
+       var tlsConfig *tls.Config
+
+       if c.transferTLS {
+               tlsConfig, err = c.server.driver.GetTLSConfig()
+               if err != nil {
+                       c.writeMessage(StatusSyntaxErrorNotRecognised, fmt.Sprintf("Problem parsing PORT: %v", err))
+                       return nil
+               }
+       }
+
        c.transfer = &activeTransferHandler{
-               raddr:    raddr,
-               settings: c.server.settings,
+               raddr:     raddr,
+               settings:  c.server.settings,
+               tlsConfig: tlsConfig,
        }
 
        return nil
@@ -31,9 +43,10 @@ func (c *clientHandler) handlePORT() error {
 
 // Active connection
 type activeTransferHandler struct {
-       raddr    *net.TCPAddr // Remote address of the client
-       conn     net.Conn     // Connection used to connect to him
-       settings *Settings    // Settings
+       raddr     *net.TCPAddr // Remote address of the client
+       conn      net.Conn     // Connection used to connect to him
+       settings  *Settings    // Settings
+       tlsConfig *tls.Config
 }
 
 func (a *activeTransferHandler) Open() (net.Conn, error) {
@@ -53,6 +66,10 @@ func (a *activeTransferHandler) Open() (net.Conn, error) {
                return nil, fmt.Errorf("could not establish active connection: %w", err)
        }
 
+       if a.tlsConfig != nil {
+               conn = tls.Server(conn, a.tlsConfig)
+       }
+
        // keep connection as it will be closed by Close()
        a.conn = conn
```

maybe I can find some time to do more tests the next weekend, meantime would help if you can apply and test the patch locally.

To compile SFTPGo against a local ftpserverlib version modify the `go.mod` for SFTPGo in a way similar to this:

```
replace (
+       github.com/fclairamb/ftpserverlib => /home/nicola/goprojects/ftpserverlib
```

replacing `/home/nicola/goprojects/ftpserverlib` with the path to your patched ftpserverlib, thank you!

**Comment by rel33** [comment]
Hi,

Patch applied, sftpgo compiled without any problem.

I confirm, that active data transfer worked.

Thank you for very quick fix. For me case can be closed.

Status:	Connecting to 172.31.SER.VER:21...
Status:	Connection established, waiting for welcome message...
Response:	220 SFTPGo 1.0.0-dev ready
Command:	AUTH TLS
Response:	234 AUTH command ok. Expecting TLS Negotiation.
Status:	Initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established.
Command:	USER test
Response:	331 OK
Command:	PASS ********
Response:	230 Password ok, continue
Command:	CLNT FileZilla
Response:	200 Good to know
Command:	OPTS UTF8 ON
Response:	200 I'm in UTF8 only anyway
Command:	PBSZ 0
Response:	200 Whatever
Command:	PROT P
Response:	200 OK
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/" is the current directory
Command:	TYPE I
Response:	200 Type set to binary
Command:	PORT 172,31,CLI,ENT,15,158
Response:	200 PORT command successful
Command:	MLSD
Response:	150 Using transfer connection
Listing:	Type=dir;Size=0;Modify=20191220195214; xxxxxxxxxxxxx
[...]
Listing:	Type=dir;Size=0;Modify=20180813144326; xxxxxxxxxxxxx
Response:	226 Closing transfer connection
Status:	Directory listing of "/" successful


Best regards,
Piotr

**Comment by fclairamb** [comment]
Thank you @rel33 & @drakkan. This is indeed a huge bug !!!
