### ISSUE TITLE
Data race caused by ABOR

### ISSUE THREAD

**Issue by fclairamb** [fclairamb/ftpserverlib#207]
Hi @drakkan,

there's a data-race that seems to be created by the new ABOR implementation.

https://github.com/fclairamb/ftpserverlib/runs/1592002486#step:6:1008

**Comment by drakkan** [comment]
Hi,

this is a bug, according to the [docs](https://golang.org/pkg/net/#Conn) multiple goroutines may invoke methods on a Conn simultaneously but we send the response for a server `STAT` as multiline, calling `WriteString` and `Flush` for each line.

A server `STAT` can happen while a transfer is in progress, we need to ensure to write the whole `STAT` response before sending a transfer open/close response, so we need to hold the transfer mutex in `STAT` method too, as we do in `ABOR`.
