### ISSUE TITLE
do not quit serve loop on temporary accept errors?

### ISSUE THREAD

**Issue by drakkan** [fclairamb/ftpserverlib#210]
Hi,

currently the [serve loop](https://github.com/fclairamb/ftpserverlib/blob/master/server.go#L183) seems to exit after any error in `listener.Accept()`.

I have not encountered any issues with this behavior until now, but if you take a look at [http.Server](https://golang.org/src/net/http/server.go#L2944)  you can see that some errors are temporary. If you like this logic, I can provide a PR (the hard part will be writing a test case). What do you think about? Thank you

**Comment by fclairamb** [comment]
That's really interesting. I didn't know this was possible. Reading [the original issue](https://github.com/golang/go/issues/6163) it seems pretty rare though. But as the standard HTTP server implements it, it's definitely worth implementing.
