### ISSUE TITLE
Allow users to extend/change handlers

### ISSUE THREAD

**Issue by ostretsov** [fclairamb/ftpserverlib#221]
First of all thanks for the library!

I want to perform some file checks right after successful `STOR` handler execution. I found the only option: extending the logger and waiting for the `Stream copy finished` event. It doesn't seem as a right way to extend functionality. What if `commandsMap` was exported?

**Comment by drakkan** [comment]
Hi,

I'm not sure to understand your question, `STOR` already calls your handlers (`OpenFile` or `GetHandle` based on what you implemented), so you can do anything you want inside your own handler.

Additionally you can use [GetLastCommand](https://github.com/fclairamb/ftpserverlib/blob/master/client_handler.go#L227) if you want to check that your handler was triggered by a `STOR` command. What is missing here?

**Comment by ostretsov** [comment]
Thanks for the quick reply!

Now I see that I can make my own implementation of the `afero.Fs` interface and return from `Fs.OpenFile` my implementation of `afero.File` with my own `Close` method where I could do whatever I need to do right after a file is closed.

Thanks for the help!
