### ISSUE TITLE
Configurable FTP client authentication method

### ISSUE THREAD

**Issue by sriramy** [fclairamb/ftpserverlib#230]
I am trying to setup an FTP server with explicit TLS in my k8s cluster. It is great that most of the features I need are already available here. One thing that I am missing though is that username/password is the only way to authenticate the client today. It would be nice to have a hook for handleUser() in MainDriver interface where an implementer can decide on the authentication method, or do that internally by having an enum in the Settings struct. 

Wondering if there is any plan to support client authentication methods?
- Certificate Only: FTP clients must use certificate authentication
- Certificate or Password: FTP clients can use password or certificate authentication
- Certificate and Password: FTP clients must use password and certificate authentication

**Comment by drakkan** [comment]
Hi,

certificate+password authentication is possible already without any modification to ftpserverlib, for example this is supported in SFTPGo.

To be able to support the other options, some changes to the library are required. I could be interested to send a patch but I'm a bit busy at the moment, it could take a while.

**Comment by sriramy** [comment]
Thanks for the quick reply, yes, I checked SFTPGo, there is code for client certificate verification.
I need some way to send StatusUserLoggedIn when client certificate is required and a SkipPassword/CertificateOnly setting.

I sent a pull request with the changes I really want. First time here, so please be patient :)
