### ISSUE TITLE
FR: customize error codes

### ISSUE THREAD

**Issue by fdefilippo** [fclairamb/ftpserverlib#239]
Hi, it is possible to put in the roadmap the possibility of having custom error code so other ([https://github.com/drakkan/sftpgo/issues/442#issuecomment-850808617](https://github.com/drakkan/sftpgo/issues/442#issuecomment-850808617) can customize the return code? 

thank you.

**Comment by fclairamb** [comment]
Hi @fdefilippo,

What do you have in mind ?

If it's a matter of handling a specific error with a different return code for all the functions that need it, it should be pretty quick:
- We can create this new error type (possibly making it wrap other errors)
- Return a different error code (`553` for example) every time it's encountered

If it's to allow to return a custom error code by specifying it in the returned error, I would also simple to implement but I don't think it would make a maintainable API. I'm open to suggestions around that.

cc @drakkan

**Comment by drakkan** [comment]
@fclairamb, I agree, we could expose some specific errors, as you suggested, and map them to a specific error code.

We could start mapping 552, 553 and maybe 452

**Comment by drakkan** [comment]
#243 allows to customize error codes, the first part of the message is still hard-coded so you will have something like this

```
553-Could not access file: <custom error string>
```

**Comment by drakkan** [comment]
@fdefilippo I did a quick test returning these new errors from SFTPGo. Before we had something like this:

```
550-Could not access file: permission denied
```

now returning `ErrFileNameNotAllowed` we have:

```
553 Could not access file: filename not allowed
```

the error text is not customizable (as requested in the review), so we now have this error for the following use cases:

- filename denied by a filter
- no upload permission
- no overwrite permission
- pre action hook failure

**Comment by drakkan** [comment]
This could be improved by wrapping errors, for example:

```
553 Could not access file: filename not allowed, no upload permission
```

I'll push these changes to SFTPGo repo later today

**Comment by fdefilippo** [comment]
thanks, I'll try It as soon as possible.
