### ISSUE TITLE
LIST command doesn't work for file

### ISSUE THREAD

**Issue by FunnyGamer** [fclairamb/ftpserverlib#240]
I use a FTP server implementation (drakkan/sftpgo) which uses this ftpserverlib and an application of mine wants to `LIST` files after a copy to validate a successful transfer. But while `LIST` command for directories works fine the `LIST` command for a single file doesn't work (returns nothing). Expected would be the listing of this file like `$ ls -l /testpath/file.txt` (in unix terminal) would do. Is there a special reason for this behaviour?

A fix for me at the moment is to modify the `handle_dirs.go#getFileList` function like this:
```
// customized to also return a List of one file if param is a file
func (c *clientHandler) getFileList(param string) ([]os.FileInfo, error) {
	if !c.server.settings.DisableLISTArgs {
		param = c.checkLISTArgs(param)
	}

	// directory or filePath
	directoryPath := c.absPath(param)

	info, err := c.driver.Stat(directoryPath)
	if err != nil {
		return nil, err
	}

	if info.IsDir() {
		if fileList, ok := c.driver.(ClientDriverExtensionFileList); ok {
			return fileList.ReadDir(directoryPath)
		}

		directory, errOpenFile := c.driver.Open(directoryPath)
		if errOpenFile != nil {
			return nil, errOpenFile
		}

		defer c.closeDirectory(directoryPath, directory)

		return directory.Readdir(-1)

	} else {
		return []os.FileInfo{info}, nil
	}
}
```

**Comment by drakkan** [comment]
Hi @FunnyGamer 

you are right, `LIST` should work for non directories too, however ftpserverlib use `getFileList` also for `MLSD` and `NLST`, and these commands must only work on directories, so we probably need to add a parameter to `getFileList` and return an error if we don't have a directory and only directories are allowed. Do you want to send a pull request including this fix and test cases? Thank you
