### ISSUE TITLE
Add support for wildcards in LIST

### ISSUE THREAD

**Issue by HunterNyan** [fclairamb/ftpserverlib#253]
Hey All,

Would it be possible for this library to support something like "LIST *.csv" to return the files matching the * as a wildcard?

Thanks,
Alice

**Comment by drakkan** [comment]
[RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#section-2.2.2) explicitly forbids it, this should be implemented client side

> Clients that desire some form of pattern matching functionality must
   obtain a listing of the relevant directory, or directories, and
   implement their own file name selection procedures.

**Comment by HunterNyan** [comment]
> [RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#section-2.2.2) explicitly forbids it, this should be implemented client side
> 
> > Clients that desire some form of pattern matching functionality must
> > obtain a listing of the relevant directory, or directories, and
> > implement their own file name selection procedures.

Sweet I had thought it was somewhere in the RFC but I couldn't find the exact RFC. . 

I will be taking this back to the vendor I'm dealing with :)
Thank you very much for providing me with this.
