### ISSUE TITLE
MLSD Response: 	550 Could not list: Not supported

### ISSUE THREAD

**Issue by zMcKracken** [fclairamb/ftpserverlib#288]
Hi,
I implemented the driver using as backend minio as well as an internal auth.
Same implementation is used in another project with SFTP and it works fine. I know it's kind of difficult explain all the project and the code for the driver, so I wonder if you can just point me to the right direction where could be the problem. When I try to connect to the FTP, the auth works great but when I should see the list of the directory I got this error:  **MLSD Response: 	550 Could not list: Not supported** 
This is the list of the command from the console, client is FileZilla:

```
Status:      	Resolving address of localhost
Status:      	Connecting to [::1]:2021...
Status:      	Connection established, waiting for welcome message...
Status:      	Insecure server, it does not support FTP over TLS.
Status:      	Logged in
Status:      	Retrieving directory listing...
Command:	PWD
Response: 	257 "/" is the current directory
Command:	TYPE I
Response: 	200 Type set to binary
Command:	EPSV
Response: 	229 Entering Extended Passive Mode (|||25615|)
Command:	MLSD
Response: 	550 Could not list: Not supported
Error:        	Failed to retrieve directory listing
```

any advice is appreciated. thanks

**Comment by drakkan** [comment]
Hi,

it is really hard to help you with the provided info. The MLSD handler calls your code, see [here](https://github.com/fclairamb/ftpserverlib/blob/757393419a47174a140b5f621c1eb566374870e5/handle_dirs.go#L228). You returned `Not supported` error from your code, only you can understand what happens :smile:
