### ISSUE TITLE
configurable port ranges for passive mode

### ISSUE THREAD

**Issue by mgenov** [fclairamb/ftpserverlib#3]
As FTP server could be packed into a docker container which requires exposed ports to be specified, it would be nice if the ftpserver allow setting of port range in the Settings. 

This is how passive mode port is taken in the current implementation In transfer_pasv.go: 
```golang
	addr, _ := net.ResolveTCPAddr("tcp", ":0")
	tcpListener, err := net.ListenTCP("tcp", addr)
	if err != nil {
		log15.Error("Could not listen", "err", err)
		return
	}
```

This is how pure-ftpd is looking for free port for data in the provided range: 

```c
    on = 1;
    if (setsockopt(datafd, SOL_SOCKET, SO_REUSEADDR,
                   (char *) &on, sizeof on) < 0) {
        error(421, "setsockopt");
        return;
    }
    dataconn = ctrlconn;
    for (;;) {
        if (STORAGE_FAMILY(dataconn) == AF_INET6) {
            STORAGE_PORT6(dataconn) = htons(p);
        } else {
            STORAGE_PORT(dataconn) = htons(p);
        }
        if (bind(datafd, (struct sockaddr *) &dataconn,
                 STORAGE_LEN(dataconn)) == 0) {
            break;
        }
        p--;
        if (p < firstport) {
            p = lastport;
        }
        if (p == firstporttried) {
            (void) close(datafd);
            datafd = -1;
            addreply_noformat(425, MSG_PORTS_BUSY);
            return;
        }
    }
```

**Comment by mgenov** [comment]
What you guys think for adding of such support ?  I can create PR for this, but I would like to know whether it's acceptable for the library. 

cc @andrewarrow @shanmoorthy @fclairamb

**Comment by andrewarrow** [comment]
sounds good to me, see https://github.com/andrewarrow/paradise_ftp/commit/83708a9aabc0bd9d1708304ffa2821eb6305016c in the original paradise_ftp that "ftpserver" was forked from. BTW should we merge this repo and paradise_ftp but keep the name paradise? I think paradise_ftp is so much more catchy name than just ftpserver.

**Comment by mgenov** [comment]
Thanks. I'll take a look. 

+1 for paradise.

**Comment by fclairamb** [comment]
@mgenov : Sorry for the late answer, I'm quite busy at the moment. 

It makes total sense, I'd like to change it soon.

I agree, it's not very catchy.
I'm not sure a merge is realistic I changed the architecture of a lot of things compared to paradise_ftp.

**Comment by mgenov** [comment]
Created  PR #4 for this change.
