### ISSUE TITLE
MLST gives incorrect response

### ISSUE THREAD

**Issue by thallgren** [fclairamb/ftpserverlib#349]
When an MLST request to the server, the server responds with

    File details
    Type=dir;Size=40;Modify=20220813121317; path
    End

This is not correct according to [RFC 3659](https://www.rfc-editor.org/rfc/rfc3659.html#section-7.2). If I understand it correctly, the response ought to be:

    250-File details
    Type=dir;Size=40;Modify=20220813121317

**Comment by drakkan** [comment]
Hi,

please provide a reproducer. If I execute the test cases and I capture a network dump with wireshark, I see the expected response

```
C> MLST 1
S> 250-File details
S> Type=file;Size=1024;Modify=20220813133357; 1
S> 250 End
```

**Comment by thallgren** [comment]
Yes, sorry. This was my mistake.

**Comment by thallgren** [comment]
I'm reopening this, because the response is not strictly in accordance with RFC 3659. The `entry` lines must be preceded with a space when sent over the control connection, e.g.:
```
250-File details
 Type=file;Size=1024;Modify=20220813133357; 1
250 End
```

**Comment by drakkan** [comment]
You are right, do you want to send a PR? Thanks

**Comment by thallgren** [comment]
I'll create a PR.

**Comment by thallgren** [comment]
#353
