### ISSUE TITLE
Could not list the contents of the bucket , throws 550 error (afero-s3)

### ISSUE THREAD

**Issue by ompushkara** [fclairamb/ftpserverlib#376]
I tried listing the root directory which is the bucket using "/" and "." , none worked . It throws a 550 error stating that Cant change directory to / Not a directory.  Note : I am able to list the contents of the directory created under a bucket though.

**Comment by drakkan** [comment]
Please try [ftpserver](https://github.com/fclairamb/ftpserver) it uses this library and afero-s3
