### ISSUE TITLE
Callbacks on File events

### ISSUE THREAD

**Issue by ghost** [fclairamb/ftpserverlib#39]
I am fairly new to Golang so not sure if this is possible at all. My question is it possible to define/invoke callback functions once certain file related events complete - such as upload, delete, rename etc.

**Comment by fclairamb** [comment]
Hi @sachinwalia2k8,

The ftpserver library doesn't do any kind of file treatment by itself. Look at the sample code,
- During the start of the server, you provide a general driver,
 [see sample server](https://github.com/fclairamb/ftpserver/blob/master/main.go#L50)
- During the authentication of the user, [see sample general driver](https://github.com/fclairamb/ftpserver/blob/master/sample/sample_driver.go#L37)
- When the client opens a file for upload or download, it calls the the `OpenFile` method of your client driver on a filestream that will be closed, [see sample client driver](https://github.com/fclairamb/ftpserver/blob/master/sample/sample_driver.go#L120) 

So, on your end it's simply a call.

**Comment by fclairamb** [comment]
I'm closing the ticket. Don't hesitate to re-open it if it's not clear enough.
