### ISSUE TITLE
Unable to use IPv6

### ISSUE THREAD

**Issue by thallgren** [fclairamb/ftpserverlib#390]
We are unable to use this project with IPv6 due to this line in the code: https://github.com/fclairamb/ftpserverlib/blob/1f3708822d88aa2c6bbdb34207d55d1c55752e70/server.go#L126.

Is there any particular reason why the `PublicHost` must be IPv4 or can that check be removed? I'd be happy to provide a PR that removes it.

**Comment by 0x6a77** [comment]
To16() includes a test for To4(), so maybe just switch to that?

**Comment by drakkan** [comment]
see #270

**Comment by fclairamb** [comment]
So, I guess we can close this issue.
