### ISSUE TITLE
[FR] Upload file size limit

### ISSUE THREAD

**Issue by MrDini123** [fclairamb/ftpserverlib#444]
Hi,

I am using this project with afero's MemMapFS and I haven't figured out whether its possible to overwrite the writer somehow. I think it would be a nice addition to add a max upload size ftp setting. If the reader that reads the incoming stream from the client exceeds the given amount of bytes, it should thow an error.

Thanks for considering this

**Comment by drakkan** [comment]
Hi,

this can be handled in your afero implementation
