### ISSUE TITLE
how to add IDLE timeout

### ISSUE THREAD

**Issue by worddevfr** [fclairamb/ftpserverlib#58]
it's not an issue but a request

how to add IDLE timeout. Example a client connects but does not execute any command. After x seconds it is disconnected automatically

**Comment by fclairamb** [comment]
As you can see it's now available in PR #59. 

It's not a big must-have as opened connections cost very little but I guess it's a feature everyone expects from a FTP server. And it can't be done at a driver level as the driver APIs work at a much higher level.

**Comment by worddevfr** [comment]
I saw your changes, these are integrated at the server level. This change will be generalized to all users. I'm (sorry) talking about a configuration per user. We have public accounts (eg anonymous), customers connect (per thousand) but do not disconnect or they stay very long to send an order. It consumes a lot of system resources. So we want for some accounts to limit the time of inactivity.

Example:
```
[[users]]
user = " anonymous"
pass = "anonymous"
dir = "public"
idle_timeout = 300 // 5 minutes

[[users]]
user = "fclairamb"
pass = "floflo"
dir = "shared"
idle_timeout = 0 // 0 = unlimited
```

**Comment by fclairamb** [comment]
Well, I'm not really interested in moving towards that direction:
- Doing this would complexify the API (namely the `ClientContext` interface) quite a bit
- Even proftpd seems to do it globally

As for the current implementation it should handle thousand of concurrent clients without any problem.

If this is something lots of other people request, I might reconsider.

On a side note: I don't think it's very important as all modern clients support sending keep-alive commands (like `NOOP`) regularly to avoid this idle timeout.

**Comment by worddevfr** [comment]
Perfect thank you for these clarifications
