### ISSUE TITLE
reload-config file

### ISSUE THREAD

**Issue by samiwt** [fclairamb/ftpserverlib#60]
Whenever you change the configuration (eg: change a password, add or delete an account) you must recompile everything, stop the server and start it! All files being sent will be lost when we stop the server :(

1. How can we reload the server-config (eg: a task to reload-config every 10 minutes)
2. Add the possibility to start / stop / restart / reload the server

Eg: ftpserver -start
```
if ServerIsStarted() {
  fmt.Println("Server is already started")
} elseif err := FtpStart(); err != nil{
  fmt.Errorf("Error! %v", err)
} else {
  fmt.Println("OK server started successful")
}
```

Same thing with -Stop, -Restart, -Reload

**Comment by fclairamb** [comment]
First of all, this project is a **library**, with a sample driver implementation. You shouldn't expect much from the server except to show that the library actually works.
That being said, more and more people seem to be interested in having a ready-to-use FTP server so it's an interesting feedback that I might use later.

To somehow address the issues raised:

- You don't need to recompile the project to build the config file. The config file shipped in the binary is only to provide a sample file if the binary is started without any option. The general idea is windows users can launch the server and only have to edit the settings.file to see the change.
- Complete reload is indeed something I should work on. It's fairly simple except for the listening port. I think the easiest option here would be to:
  - Add a method to the library to reload settings
  - If the listening address is different from the current one: Start a new instance of the listener, close the previous one but let connected clients use the previous one

**Comment by samiwt** [comment]
Yes, it would be good! :)

**Comment by samiwt** [comment]
I do not know too much the GoLang language, it would be nice if someone added this option! That's all I needed to use this library. Thank you very much
