### ISSUE TITLE
Memory leak: file is not closed if TransferOpen() fails

### ISSUE THREAD

**Issue by marshallbrekka** [fclairamb/ftpserverlib#69]
https://github.com/fclairamb/ftpserver/blob/d06e1a0d4a20bf8a311961952b15c550a1acbfd9/server/handle_files.go#L22-L35

The file opened on line 22 is never closed if the `TransferOpen()` call fails.
You could of course call `file.Close()` within that else block, my only concern is that still results in an empty file being created.

Another option is to call `TransferOpen()` first, and then attempt to open the file.

I can submit a PR once a solution is agreed upon.

**Comment by fclairamb** [comment]
I just checked, in that scenario, proftpd creates an empty file. 

So I think it's quite acceptable to behave the same way.

**Comment by fclairamb** [comment]
PR #71 fixes this.
