### ISSUE TITLE
Drop log15 ?

### ISSUE THREAD

**Issue by fclairamb** [fclairamb/ftpserverlib#7]
I saw a fork ( https://github.com/AntiPaste/ftpserver ) that dropped log15 logging.

I don't think this is a good idea, I find structured logging to be a very important concept of any modern software but I wonder what **you** think about it.

Please vote:
- 👎  for keeping log15
- 👍  for dropping log15

**Comment by fclairamb** [comment]
Not a lot of votes :)

**Comment by fclairamb** [comment]
Actually I'm thinking we could switch to [go-kit logs](
https://github.com/go-kit/kit/tree/master/log). The whys are [here](http://go-talks.appspot.com/github.com/ChrisHines/talks/structured-logging/structured-logging.slide). I think it's especially relevant for a library.

**Comment by mgenov** [comment]
go-kit has nice features for reporting metadata and metrics which could be used by the infrastructure.

+1 for go-kit.

**Comment by fclairamb** [comment]
This has been done in PR #33 by replacing log15 by log-kit.
