### ISSUE TITLE
[Discussion] Handle client sudden disconnections

### ISSUE THREAD

**Issue by fclairamb** [fclairamb/ftpserverlib#72]
Following up on #70 ...

If a client disconnects halfway through the upload, the current driver doesn't allow to detect anything.

Subjects to address:
- Do we have a correct way to handle that in the first place? What is the difference between a successful upload and one that isn't? If a TCP connection stops halfway through, how can we detect it?

**Comment by sheerun** [comment]
I think it would be good idea to attach context.Context to ClientContext so implementations can react to closed connection. It would be good to do so even before you figure out how to properly detect it

**Comment by fclairamb** [comment]
I'm closing this because:
- We are the root of a possible context, the library is not doing anything cancellable, it's only reacting to short commands and piping streams. So I think it makes sense but on the client driver implementation and as such, I'll leave it to the client drivers (in this case the afero ones) to use it.
- I don't see any place where it could make sense, to be more specific:
  - If a control connection closes, it doesn't mean the transfer connection should be canceled
  - If a transfer connection closes, then that's the end of the file
