### ISSUE TITLE
What is the variable "NonStandardActiveDataPort"?

### ISSUE THREAD

**Issue by samiwt** [fclairamb/ftpserverlib#88]
in file ftpserver/server/driver.go

What is the variable "NonStandardActiveDataPort"?
```
type Settings struct {
...
	**NonStandardActiveDataPort** bool _// Allow to use a non-standard active data port_
...
}
```

An example for "... non-standard active data port" ?

Thank

**Comment by fclairamb** [comment]
A [RFC 1579 for a firewall-friendly FTP](https://tools.ietf.org/html/rfc1579) recommends using port 20 for all active data transfer.

As this setting is not clear enough, I will change it to `ActiveTransferPortNon20` and add some documentation.
