### ISSUE TITLE
An error occurs when connecting to the server

### ISSUE THREAD

**Issue by php-info** [fclairamb/ftpserverlib#91]
Google Translation: French-> English

# An error occurs when connecting to the server with "Active" mode and SSL or TLS encrypted connection

Example: Configure FileZilla Ftp Client with:

-Transfer mode: **Active**
-Encryption: **SSL or TLS**

=> Error detected: Unable to connect to the server (with a login and password) with this configuration.

Thanks

**Comment by fclairamb** [comment]
I'm definitely interested in the exact logs or reproducer you might have around that.

I did test it in that configuration.

Considering this issue is 1 year old, I would be surprised if you did send me the logs, so I'll go ahead and close this issue.
